#!/system/bin/sh
#clears various junk

rm -rf /cache/*
rm -rf /data/anr/*
#rm -rf /data/log/*
rm -rf /data/system/cache/*
rm -rf /data/system/dropbox/*
rm -rf /data/system/procstats/*
rm -rf /data/system/recent_images/*
rm -rf /data/system/usagestats/*
rm -rf /data/tombstones/*
